docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind

  before_script:
    - pwd
    - apk update
    - apk add git
    - git version 
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - git pull origin master

 script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" --password-stdin
    - docker-compose build 
    - docker-compose up -d
  tags:
    - dind
  only:
    - master
   
