docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - ls 
    - whoami
    - apk update
    - apk add git
    - git version 
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - git remote -v
    - git clone git@gitlab.diginov.tech:root/devopslaravel.git
    - ls 
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build
    - docker-compose up -d
    - docker tag devopslaravel_attendize_nginx:latest dolking/diginov:nginx-v-1
    - docker tag devopslaravel_attendize_app dolking/diginov:app-v-1
    - docker tag mysql:5 dolking/diginov:db-v-1
    - docker push dolking/diginov:nginx-v-1
    - docker push dolking/diginov:app-v-1
    - docker push dolking/diginov:db-v-1

  tags:
    - dind
  only:
    - master
   
