docker-build-master:
  image: tmaier/docker-compose:latest
  stages: 
   - build
   - push 
   
  build:
  services:
    - docker:dind

  before_script:
    - pwd
    - apk update
    - apk add git
    - git version 
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - git pull origin master
   
  script: 
    - docker info
    - docker-compose --version
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"   
    - docker-compose build 
    - docker-compose up -d

  push:

  before_script:
    - echo hello
  script: 
    - echo helllo
  tags:
    - dind
  only:
    - master
   
