before_script:
  - apk add --no-cache python py2-pip
  - pip install --no-cache-dir docker-compose
  - docker-compose -v
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - publish

publish-docker:
  stage: publish
  image: docker
  script:
   - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
   - export IMAGE_NAME="dolking/diginov"
   - export VERSION_TAG_nginx="nginx-v.1"
   - docker-compose build 
   - docker commit -m 'Added My nginx ' ica-backoffice_attendize_nginx_1 ${IMAGE_NAME}:${VERSION_TAG_nginx}
   - docker push ${IMAGE_NAME}:${VERSION_TAG_nginx}
