docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - ls 
    - whoami
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build
    - docker-compose up -d
    - docker tag devopslaravel_attendize_nginx:latest dolking/diginov:nginx-v-1
    - docker tag devopslaravel_attendize_app_1 dolking/diginov:app-v-1
    - docker tag devopslaravel_attendize_db_1 dolking/diginov:db-v-1
    - docker push dolking/diginov:nginx-v-1
    - docker push dolking/diginov:app-v-1
    - docker push dolking/diginov:db-v-1

  tags:
    - dind
  only:
    - master
   
