docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  script:
    - pwd 
    - docker info
    - docker-compose --version
    - docker-compose build 
    - docker-compose up 
  tags:
    - dind
  only:
    - master

   