docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - apk update
    - apk add git
    - git version 
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - git fetch; [ $(git rev-parse HEAD) = $(git rev-parse @{u}) ] \ && echo "Up to date" || echo "Not up to date"
    - git remote -v
    - git pull origin master
    - git status
    - git fetch; [ $(git rev-parse HEAD) = $(git rev-parse @{u}) ] \ && echo "Up to date" || echo "Not up to date"

   
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build 
    - docker-compose up -d
    - echo hello world
  tags:
    - dind
  only:
    - master
   
