image: docker:18.09

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2  
  DOCKER_TLS_CERTDIR: ""  
 

before_script:
  - docker info 

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - master
  tags:
  - docker


