docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - apk update
    - apk add git
    - git version 
    
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - mkdir -p ~/.ssh
    - cat gitlab-known-hosts >> ~/.ssh/known_hosts
    
    - git pull origin master
    - git status
   
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build 
    - docker-compose up -d
    - echo hello world
  tags:
    - dind
  only:
    - master
   
