docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  script:
    - pwd
    - cd /var/www/html/myapp/ica-backoffice 
    - docker info
    - docker-compose --version
    - docker-compose build 
    - docker-compose up -d 
  tags:
    - dind
  only:
    - master
   
