stages:
  - build_push



build-push-image:
  stage: build_push
  # the tag 'dind' advices only GitLab runners using this tag to pick up that job
  tags: 
    - dhia
  script:
    - pwd
    - apk update -y
    - apk install net-tools -y
    - ifconfig
    