image: docker:18.09
services:
  - docker:18.09-dind
variables:
       DOCKER_DRIVER: overlay2
       DOCKER_TLS_CERTDIR: ""
stages:
 - build
 - test
build:
 stage: build
 before_script:
  - pwd
  - docker info
test:
  - echo "hello"
  
 only:
       - master
 tags:
       - dind
   