docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - ls 
    - whoami
    - su deploy 
    - docker info  
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build --pull
    - docker images
    - echo what should i do !
    
  tags:
    - dind
  only:
    - master
   
