  image: docker:18.09
  
  stage: build
  tags:
  - docker
  services:
   - name: docker:dind


  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
     - pwd 
     - ls
     - whoami
     - docker info
     - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} 
  script:
    # Download bash:   
     - export IMAGE_NAME="dolking/diginov"
     - docker-compose build 
     - docker commit -m 'Added My nginx ' ica-backoffice_attendize_nginx_1 ${IMAGE_NAME}:${VERSION_TAG}
     - docker push ${IMAGE_NAME}:${VERSION_TAG}

  # Only build off of master branch:
  only:
    - master

  