docker-build:
  tags:
  - docker
  stage: build

  services:
   - name: docker:dind
  image:
   - docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
     - pwd 
     - docker info
     
  script:
    # Download bash:   
     - export IMAGE_NAME="dolking/diginov"
     - docker-compose build 
     - docker commit -m 'Added My nginx ' ica-backoffice_attendize_nginx_1 ${IMAGE_NAME}:${VERSION_TAG}
     - docker push ${IMAGE_NAME}:${VERSION_TAG}

  # Only build off of master branch:
  only:
    - master

  