image: docker:18.09
services:
  - docker:18.09-dind
   
variables:

  DOCKER_HOST: tcp://docker:2375/
    # Use the overlayfs driver for improved performance:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
stages: 
  - build 
  - test 

build:
  stage: build 
  before_script: 
    - pwd 
    - docker info
    - apk add --no-cache docker-cli python3
    - apk add --no-cache --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip3 install docker-compose

  tags:
    - dind
   