docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - pwd
    - docker info  
  script: 
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker-compose build
    - docker-compose up 
    - docker images
<<<<<<< HEAD
    - docker logout
=======
    - docker ps 
>>>>>>> 546d2f290b775191d46f6ac3b830d7c27207b912
    
  tags:
    - dind
  only:
    - master
   
