image: docker:18.09
services:
      - docker:18.09-dind
    variables:
       DOCKER_DRIVER: overlay2
       DOCKER_TLS_CERTDIR: ""
    stages:
      - build
    stage: build
      before_script:
      - pwd
      - docker info
     only:
       - master
     tags:
       - dind
   