docker-build-master:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - docker info
    - apt-update
    - apt get install curl
    - curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose --version
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} 

    
  script:
    - echo "hello world"
  only:
    - master
  tags:
    - dind