image: docker:18.09
services:
- docker:18.09
- dind
variables:
#DOCKER_HOST: tcp://docker:2375/
# Use the overlayfs driver for improved performance:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
stages:
- build
stage: build
before_script:
- pwd
- docker info
tags:
- docker
# Only build off of master branch:
only:
- master

