docker-build-master:
  image: tmaier/docker-compose:latest
  stage: build
  services:
    - docker:dind
  script:
    - pwd
    - apk update
    - apk add git
    - git version 
    - git config --global user.name "Dhiaedddine Ammar"
    - git config --global user.email "dammar@stage.diginov.tech"
    - git fetch --all
    - git reset --hard origin/master
    - git pull
    - docker info
    - docker-compose --version
    - docker-compose build 
    - docker-compose up -d
    - echo done 
  tags:
    - dind
  only:
    - master
   
