docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - pwd 
    - docker info
    - apk add --no-cache docker-cli python3 pip3
    - apk add --no-cache --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make
    - pip3 install docker-compose
  tags:
    - dind
  only:
    - master

   