version: "3.8"
services:

  attendize_app:
    image: dolking/app
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - attendize_db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: attendize-app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: attendize_db
      DB_PORT: 3306
    networks:
      - app_network

  attendize_nginx:
    image: dolking/nginx
    build:
      context: ./docker-nginx/. # The path of the Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    environment:
      NGINX_FPM_HOST: attendize_app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - attendize_app
    networks:
      - app_network

  attendize_db:
    image: mysql:5
    restart: always
    
    environment:
      MYSQL_DATABASE: "preprodica"
      MYSQL_ROOT_PASSWORD: "Str0ngDBP@ssw0rd"
      MYSQL_USER: "dhia"
      MYSQL_PASSWORD: "dhiaammar"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"      
    ports:
      - "3306:3306"
    volumes:
      - "./storage/db-data:/var/lib/mysql"

    networks:
      - app_network

networks:
  app_network:
    driver: bridge

